# Generated by Django 3.2 on 2021-04-22 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pet',
            table='pet',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
