"""empty message

Revision ID: aa91817de394
Revises: 
Create Date: 2021-04-25 12:24:17.654345

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa91817de394'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person')
    op.drop_table('user')
    op.drop_table('pet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('pet_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('species', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('discord_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('color', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('closeness', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('size', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ability_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('rarity', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('owner', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('stats', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='api_pet_pkey')
    )
    op.create_table('user',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('eggs', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('discord_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('coins', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='api_user_pkey')
    )
    op.create_table('person',
    sa.Column('key', sa.BIGINT(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('correct', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('incorrect', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('current_question', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('key', name='person_pkey')
    )
    # ### end Alembic commands ###
