"""empty message

Revision ID: faf1e0a0a88a
Revises: 6561067ed2c0
Create Date: 2021-04-27 11:56:59.821969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faf1e0a0a88a'
down_revision = '6561067ed2c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', sa.String(length=64), nullable=True))
    op.drop_index('ix_user_username', table_name='user')
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=True)
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.drop_column('user', 'user_id')
    # ### end Alembic commands ###
